4 Python y JS/PROJECTCLASE12_ad77m76d/AEROLINEA/urls.py
from django.urls import path, include
from . import views

app_name = "AEROLINEA"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:vuelo_id>', views.vuelo, name="vuelo"),
    path('vuelo_alta', views.vuelo_alta, name="vuelo_alta"),
    path('<int:vuelo_id>/vuelo_modificar', views.vuelo_modificar, name="vuelo_modificar"),
    path('<int:vuelo_id>/vuelo_eliminar', views.vuelo_eliminar, name="vuelo_eliminar"),
    path('<int:vuelo_id>/reserva', views.reserva, name="reserva")
]

4 Python y JS/PROJECTCLASE12_ad77m76d/PROJECTCLASE12/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("AEROLINEA.urls")),
    path('AEROLINEA/', include("AEROLINEA.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registrarse/', include('USUARIOS.urls')),
]

4 Python y JS/PROJECTCLASE12_ad77m76d/USUARIOS/urls.py
from django.urls import path, include
from . import views

app_name = "USUARIOS"
urlpatterns = [
    path('', views.registrarse, name="registrarse"),
]

4 Python y JS/PROJECTCLASE12_ad77m76d/AEROLINEA/models.py
from django.db import models

# Create your models here.
class Aeropuerto(models.Model):
    codigo = models.CharField(max_length=3)
    ciudad = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.ciudad} ({self.codigo})"
        
class Vuelo(models.Model):
    origen = models.ForeignKey(Aeropuerto, on_delete=models.CASCADE, related_name="salidas")
    destino = models.ForeignKey(Aeropuerto, on_delete=models.CASCADE, related_name="arribos")
    duracion = models.IntegerField()

    def __str__(self):
        return f"Vuelo #{self.id}: {self.origen} hacia {self.destino}"

class Pasajero(models.Model):
    nombre = models.CharField(max_length=64)
    apellido = models.CharField(max_length=64)
    vuelos = models.ManyToManyField(Vuelo, blank=True, related_name="pasajeros")

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

4 Python y JS/PROJECTCLASE12_ad77m76d/USUARIOS/models.py
from django.db import models

# Create your models here.

4 Python y JS/PROJECTCLASE12_ad77m76d/AEROLINEA/forms.py
from django import forms
from .models import Vuelo

class FormVueloCustom(forms.ModelForm):
    #campos del modelo
    class Meta:
        model = Vuelo
        fields = ('origen', 'destino', 'duracion')
        widgets = {
            'origen': forms.TextInput(attrs={'class': 'estilo_origen'}),
            'destino': forms.TextInput(attrs={'class': 'estilo_destino'}),
            'duracion': forms.TextInput(attrs={'class': 'estilo_duracion'}),
        }

4 Python y JS/PROJECTCLASE12_ad77m76d/USUARIOS/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistroForm(UserCreationForm):
    username = forms.CharField(
        label='Usuario', widget=forms.TextInput(attrs={'class': 'usuario'}), max_length=150, required=True, help_text='Requerido. 150 caracteres o menos. Letras, dígitos y @ /. / + / - / _ solamente.')
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='Requerido. Al menos 8 caracteres y no pueden ser todos numeros.')
    password2 = forms.CharField(
        label='Repetir Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='Requerido. Ingrese la misma contraseña que antes, para verificación.')
    first_name = forms.CharField(
        label='Nombre', widget=forms.TextInput(attrs={'class': 'nombre'}), max_length=30, required=False, help_text='Opcional.')
    last_name = forms.CharField(
        label='Apellido', widget=forms.TextInput(attrs={'class': 'apellido'}), max_length=30, required=False, help_text='Opcional.')
    email = forms.EmailField(
        label='Email', widget=forms.TextInput(attrs={'class': 'email'}), max_length=254, required=True, help_text='Se requiere una direccion de email valida.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

4 Python y JS/PROJECTCLASE12_ad77m76d/AEROLINEA/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import *
from .models import Vuelo, Pasajero
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required

# Create your views here.

def index(request):
    return render(request,"vuelos/index.html", {
        "lista_vuelos": Vuelo.objects.all()
    })

@permission_required('AEROLINEA.view_vuelo')
def vuelo(request, vuelo_id):
    vuelo = Vuelo.objects.get(id=vuelo_id)
    pasajeros = vuelo.pasajeros.all()
    no_son_pasajeros = Pasajero.objects.exclude(vuelos=vuelo).all()
    return render(request, "vuelos/vuelo.html", {
        "vuelo": vuelo,
        "pasajeros": pasajeros,
        "no_son_pasajeros": no_son_pasajeros
    })

@permission_required('AEROLINEA.add_vuelo')
def vuelo_alta(request):
    #VueloForm = modelform_factory(Vuelo, fields=("origen", "destino", "duracion"))
    if request.method == "POST":
        form = FormVueloCustom(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = FormVueloCustom()
        return render(request, "vuelos/vuelo_alta.html", {
            "formset": form
        })

@permission_required('AEROLINEA.change_vuelo')
def vuelo_modificar(request, vuelo_id):
    un_vuelo = get_object_or_404(Vuelo, id=vuelo_id)
    
    if request.method == "POST":     
        form = FormVueloCustom(request.POST, instance = un_vuelo) 
        if form.is_valid():
            form.save()
            return render(request,"vuelos/index.html", {
                "lista_vuelos": Vuelo.objects.all()
            })
    else:
        form = FormVueloCustom(instance = un_vuelo)
        return render(request, 'vuelos/vuelo_modificar.html', {
            "un_vuelo": un_vuelo,
            "form": form
        })

@permission_required('AEROLINEA.delete_vuelo')
def vuelo_eliminar(request, vuelo_id):
    un_vuelo = get_object_or_404(Vuelo, id=vuelo_id)
    un_vuelo.delete()
    return render(request,"vuelos/index.html", {
        "lista_vuelos": Vuelo.objects.all()
    })

@login_required
def reserva(request, vuelo_id):
    if request.method == "POST":
        vuelo = Vuelo.objects.get(pk=vuelo_id)
        pasajero_id = int(request.POST["pasajero"])
        pasajero = Pasajero.objects.get(pk=pasajero_id)
        pasajero.vuelos.add(vuelo)
        return HttpResponseRedirect(reverse("AEROLINEA:vuelo", args=(vuelo.id,)))

4 Python y JS/PROJECTCLASE12_ad77m76d/USUARIOS/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import *

def registrarse(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            form.save()          
            return HttpResponseRedirect(reverse('login'))
    else:
        form = RegistroForm()
    return render(request, 'registration/registro.html', {
        'form': form
        })

4 Python y JS/PROJECTCLASE12_ad77m76d/AEROLINEA/templates/vuelos/index.html
{% extends "vuelos/layout.html" %}
{% block body %}
    <h1>Vuelos</h1>
    <ul>
        {% for un_vuelo in lista_vuelos %}
            <li>
               
                <a href="{% url 'AEROLINEA:vuelo' un_vuelo.id %}">Ver Vuelo #{{un_vuelo.id}}</a> / 
                
                {% if perms.AEROLINEA.change_vuelo %}
                <a href="{% url 'AEROLINEA:vuelo_modificar' un_vuelo.id %}">Editar</a> / 
                {% endif %}
                {% if perms.AEROLINEA.delete_vuelo %} 
                <a href="{% url 'AEROLINEA:vuelo_eliminar' un_vuelo.id %}">Eliminar</a>  
                {% endif %}
                ---
                {{un_vuelo.origen}} hacia {{un_vuelo.destino}}</li>
        {% endfor %}
    </ul>
    {% if perms.AEROLINEA.add_vuelo %}
    <a href="{% url 'AEROLINEA:vuelo_alta'%}">Alta de Vuelo</a>
    {% endif %}
{% endblock %}

4 Python y JS/PROJECTCLASE12_ad77m76d/AEROLINEA/templates/vuelos/layout.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Vuelos</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <p>Usuario: {{ user.get_username }}</p>
            <p><a href="{% url 'logout'%}?next={{request.path}}">Desconectarse</a></p>
            {% block body %}
            {% endblock %}
        {% else %}
            <p>No podra visualizar los datos de los vuelos sin estar conectado.</p>
            <p><a href="{% url 'login'%}?next={{request.path}}">Acceder</a></p>
        {% endif %} 
    </body>
</html>

4 Python y JS/PROJECTCLASE12_ad77m76d/AEROLINEA/templates/vuelos/vuelo.html
{% extends "vuelos/layout.html" %}
{% block body %}
<h2>Vuelo</h2>
<h3>Lista de Pasajeros</h3>
<ul>
    {% for un_pasajero in pasajeros %}
        <li>{{ un_pasajero }}</li>
    {% empty %}
        <li>No hay pasajeros registrados.</li>
    {% endfor %}
</ul>
<a href="{% url 'AEROLINEA:index' %}">Volver a la lista</a>
<h3>Reserva</h3>
<form action="{% url 'AEROLINEA:reserva' vuelo.id %}" method="post">
    {% csrf_token %}
    <select name="pasajero" id="">
        {% for un_pasajero in no_son_pasajeros %}
            <option value="{{ un_pasajero.id }}">{{ un_pasajero }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="RESERVAR">
</form>
{% endblock %}

4 Python y JS/PROJECTCLASE12_ad77m76d/AEROLINEA/templates/vuelos/vuelo_alta.html
{% extends "vuelos/layout.html" %}
{% block body %}
<h3>Alta de Vuelo</h3>
<form action="{% url 'AEROLINEA:vuelo_alta' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="GUARDAR">
</form>
{% endblock %}

4 Python y JS/PROJECTCLASE12_ad77m76d/AEROLINEA/templates/vuelos/vuelo_modificar.html
{% extends "vuelos/layout.html" %}
{% block body %}
<h3>Modificar Vuelo</h3>
<form action="{% url 'AEROLINEA:vuelo_modificar' un_vuelo.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="GUARDAR">
</form>
{% endblock %}