4 Python y JS/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("sitio.urls")),
    path('sitio/', include("sitio.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

4 Python y JS/blog/sitio/urls.py
from django.urls import path
from . import views

app_name = "sitio"
urlpatterns = [
    path('', views.index, name="index"),
    path('filtro_secciones/<int:seccion_id>', views.filtro_secciones, name="filtro_secciones"),
    path('<int:articulo_id>', views.articulo, name="articulo"),
    path('articulo_alta', views.articulo_alta, name="articulo_alta"),
    path('articulo_editar/<int:articulo_id>', views.articulo_editar, name="articulo_editar"),
    path('articulo_eliminar/<int:articulo_id>', views.articulo_eliminar, name="articulo_eliminar"),
    path('leer_mas_tarde/<int:articulo_id>', views.leer_mas_tarde, name="leer_mas_tarde")
]

4 Python y JS/blog/sitio/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Seccion(models.Model):
    descripcion = models.CharField(max_length=64, null=False)

    def __str__(self):
        return f"{self.descripcion}"

class Articulo(models.Model):
    seccion = models.ForeignKey(Seccion, on_delete=models.CASCADE, related_name="clasificacion_seccion")
    fecha_publicacion = models.DateField(null= False)
    titulo = models.CharField(max_length=250, null=False)
    contenido = models.CharField(max_length=2000, null=False)
    imagen = models.FileField(upload_to='imagenes/')
    publicador = models.ForeignKey(User, on_delete=models.CASCADE, related_name="publicador")

    def __str__(self):
        return f"{self.fecha_publicacion} - {self.titulo} ({self.publicador})"

class LeerMasTarde(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usuario")
    publicaciones = models.ManyToManyField(Articulo)

    def __str__(self):
        return f"{self.usuario} - {self.publicaciones}"

4 Python y JS/blog/sitio/forms.py
from django import forms
from .models import Articulo

class FormArticulo(forms.ModelForm):

    #campos del modelo
    class Meta:
        model = Articulo
        fields = ('seccion', 'fecha_publicacion', 'titulo', 'contenido', 'imagen')
        widgets = {
            'fecha_publicacion': forms.SelectDateWidget(attrs={'class': 'pub_fecha_publicacion'}),
            'titulo': forms.TextInput(attrs={'class': 'pub_titulo'}),
            'contenido': forms.Textarea(attrs={'class': 'pub_contenido'}),
            'imagen': forms.FileInput(attrs={'name':'imagen_adjunta', 'class': 'pub_imagen'}),
        }

4 Python y JS/blog/sitio/views.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404
from .forms import *
from .models import Articulo, Seccion
from django.utils import timezone

# from django.contrib.auth.decorators import login_required
# from django.contrib.auth.decorators import permission_required

# Create your views here.

def index(request):
    return render(request,"blog/index.html", {
        "lista_articulos": Articulo.objects.all(),
        "lista_secciones": Seccion.objects.all(),
    })

def articulo(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    return render(request, "blog/articulo.html", {
        "articulo": un_articulo
    })

def articulo_alta(request):
    if request.method == "POST":
        user = User.objects.get(username=request.user)
        form = FormArticulo(request.POST, request.FILES, instance=Articulo(imagen=request.FILES['imagen'], publicador=user))      
        if form.is_valid():
            form.save()
            return render(request,"blog/index.html", {
                "lista_articulos": Articulo.objects.all()
            })
    else:
        form = FormArticulo(initial={'fecha_publicacion':timezone.now()})
        return render(request, "blog/articulo_nuevo.html", {
            "form": form
        })

def articulo_editar(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    if request.method == "POST":  
        user = User.objects.get(username=request.user)   
        un_articulo.publicador = user
        form = FormArticulo(data=request.POST, files=request.FILES, instance=un_articulo)
        if form.is_valid():
            form.save()
            return render(request,"blog/index.html", {
                "lista_articulos": Articulo.objects.all()
            })
    else:
        form = FormArticulo(instance = un_articulo)
        return render(request, 'blog/articulo_edicion.html', {
            "articulo": un_articulo,
            "form": form
        })

def articulo_eliminar(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    un_articulo.delete()
    return render(request,"blog/index.html", {
        "lista_articulos": Articulo.objects.all()
    })

def filtro_secciones(request, seccion_id):
    una_seccion = get_object_or_404(Seccion, id=seccion_id)
    queryset = Articulo.objects.all()
    queryset = queryset.filter(seccion=una_seccion)
    return render(request,"blog/index.html", {
        "lista_articulos": queryset,
        "lista_secciones": Seccion.objects.all(),
        "seccion_seleccionada": una_seccion
    })

def ver_leer_mas_tarde(request):
    pass

def add_leer_mas_tarde(request, articulo_id):
    pass

def leer_mas_tarde(request, articulo_id):
    pass

4 Python y JS/blog/sitio/templates/blog/articulo.html
{% extends "blog/layout.html" %}
{% block content %}
<h2>{{ articulo.titulo }}</h2>
<div class="alert alert-info" role="alert">{{ articulo.seccion }}</div>
<p><span class="publicacion_fecha" >{{ articulo.fecha_publicacion }}</span></p>
<p><img src="{{ media_url  }}{{ articulo.imagen.url }}" alt="{{ articulo.imagen.name }}" /></p>
<h3>Contenido:</h3>
<p id="contenido">{{ articulo.contenido |safe }}</p>
<p>Publicado por <span class="badge badge-secondary">{{ articulo.publicador }}</span></p>
<a href="{% url 'sitio:index'%}">Volver</a>
{% endblock %}

4 Python y JS/blog/sitio/templates/blog/articulo_edicion.html
{% extends "blog/layout.html" %}
{% block content %}
<h3>Publicar un Articulo</h3>
<form enctype="multipart/form-data" action="{% url 'sitio:articulo_editar' articulo.id %}" method="post" >
    {% csrf_token %}
    <div class="form-group row">
        <label for="seccion_input"  class="col-sm-2 col-form-label">Seccion:</label> {{ form.seccion }} {{ form.seccion.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input"  class="col-sm-2 col-form-label">Titulo:</label> {{ form.titulo }} {{ form.titulo.errors }}
    </div>
    <div class="form-group row">
        <label for="publicacion_input"  class="col-sm-2 col-form-label">Fecha de Publicacion:</label> {{ form.fecha_publicacion }} {{ form.fecha_publicacion.errors }}
    </div>
    <div class="form-group row">
        <label for="imagen_input"  class="col-sm-2 col-form-label">Imagen Adjunta:</label> {{ form.imagen }} {{ form.imagen.errors }}
    </div>
    <div class="form-group row"  class="col-sm-2 col-form-label">
        <label for="contenido_input">Contenido:</label> {{ form.contenido }} {{ form.contenido.errors }}
        <script>$("#id_contenido").removeAttr("required");</script>
    </div>
    <div class="col-auto">
        <a class="btn btn-secondary" href="{% url 'sitio:index'%}">Volver</a>
        <input type="submit" class="btn btn-primary" value="Editar">
    </div>
</form>
<a href="{% url 'sitio:index'%}">Volver</a>
{% endblock %}

4 Python y JS/blog/sitio/templates/blog/articulo_nuevo.html
{% extends "blog/layout.html" %}
{% block content %}
<h3>Publicar un Articulo</h3>
<form enctype="multipart/form-data" action="{% url 'sitio:articulo_alta' %}" method="post" >
    {% csrf_token %}
    <div class="form-group row">
        <label for="seccion_input"  class="col-sm-2 col-form-label">Seccion:</label> {{ form.seccion }} {{ form.seccion.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input"  class="col-sm-2 col-form-label">Titulo:</label> {{ form.titulo }} {{ form.titulo.errors }}
    </div>
    <div class="form-group row">
        <label for="publicacion_input"  class="col-sm-2 col-form-label">Fecha de Publicacion:</label> {{ form.fecha_publicacion }} {{ form.fecha_publicacion.errors }}
    </div>
    <div class="form-group row">
        <label for="imagen_input"  class="col-sm-2 col-form-label">Imagen Adjunta:</label> {{ form.imagen }} {{ form.imagen.errors }}
    </div>
    <div class="form-group row"  class="col-sm-2 col-form-label">
        <label for="contenido_input">Contenido:</label><br> {{ form.contenido }} {{ form.contenido.errors }}
        <script>$("#id_contenido").removeAttr("required");</script>
    </div>
    <div class="col-auto">
        <a class="btn btn-secondary" type="button" href="{% url 'sitio:index'%}">Volver</a>
        <input type="submit" class="btn btn-primary" value="Publicar">
    </div>
</form>

{% endblock %}

4 Python y JS/blog/sitio/templates/blog/index.html
{% extends "blog/layout.html" %}
{% block content %}
    <h2>Articulos</h2>
    {% if seccion_seleccionada %}
        <div class="alert alert-info" role="alert">{{ seccion_seleccionada }}</div>
    {% else %}
        <div class="alert alert-info" role="alert">Todos los Articulos</div>
    {% endif %}
    <ul>
        {% for un_articulo in lista_articulos %}
            <li>              
                <a href="{% url 'sitio:articulo' un_articulo.id %}">Ver #{{un_articulo.id}}</a> /                
                {% if perms.sitio.change_articulo %}
                <a href="{% url 'sitio:articulo_editar' un_articulo.id %}">Modificar</a> / 
                {% endif %}
                {% if perms.sitio.delete_articulo %} 
                <a href="{% url 'sitio:articulo_eliminar' un_articulo.id %}">Eliminar</a>  
                {% endif %}
                --- {{un_articulo}}
            </li>
        {% empty %}
            <li>No hay articulos en ésta Sección.</li>
        {% endfor %}
    </ul>
    {% if perms.sitio.add_articulo %}
    <a href="{% url 'sitio:articulo_alta'%}">Escribir un Articulo</a>
    {% endif %}
{% endblock %}

4 Python y JS/blog/sitio/templates/blog/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Desarrollo Web con Python y JavaScript</title>
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
        <script src="{% static 'scripts.js' %}"></script>
    </head>
    <body>
        <div class="container">
            <header>
                <div id="bloque_login">
                    {% if user.is_authenticated %}
                        Estas conectado como: {{ user.get_username }} <a role="button" class="btn btn-outline-warning btn-sm" href="{% url 'logout'%}?next={{request.path}}">Salir</a>
                    {% else %}                  
                        <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'login'%}?next={{request.path}}">Acceder</a>
                    {% endif %} 
                </div>
                <h1>Mi Blog Django</h1>
            </header>
            <nav id="menu_principal" class="navbar navbar-expand-lg navbar-light bg-light">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sitio:index' %}">
                            Articulos
                        </a>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <a type="button" class="nav-link dropdown-toggle" data-toggle="dropdown">
                            Secciones
                            </a>
                            <div class="dropdown-menu">
                                {% for seccion in lista_secciones %}
                                    <a class="dropdown-item" href="{% url 'sitio:filtro_secciones' seccion.id%}">{{ seccion }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                <ul>
            </nav>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>